[tool.isort]
sections = [ "FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER" ]
default_section = "LOCALFOLDER"
known_third_party = ["musicbrainzngs", "mutagen", "PyQt5"]
length_sort = false
skip_glob = ["**/ui_*.py"]
combine_as_imports = true
float_to_top = false
force_grid_wrap = 2
force_sort_within_sections = true
include_trailing_comma = true
indent = "    "
lines_after_imports = 2
multi_line_output = 3
order_by_type = true
use_parentheses = true
